### ISSUE TITLE
Command error

### ISSUE THREAD

**Issue by nkomarn** [aasmus/PvPToggle#14]
```
[16:20:14 ERROR]: null                                                                                                                                             
org.bukkit.command.CommandException: Unhandled exception executing command 'pvp' in plugin PvPToggle v1.6.6                                                        
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.14.4.jar:git-Paper-221]                                                     
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-221]                                             
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-221]                                   
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800) ~[patched_1.14.4.jar:git-Paper-221]                            
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608) ~[patched_1.14.4.jar:git-Paper-221]                                        
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.4.jar:git-Paper-221]                                          
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.4.jar:git-Paper-221]                                           
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-221]                at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-221]                                                           
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-221]                             
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-221]                                 
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-221]                             
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-221]                                         
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-221]                                
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.14.4.jar:git-Paper-221]                               
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1158) ~[patched_1.14.4.jar:git-Paper-221]                                          
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-221]                                         
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]                                                                                                     
Caused by: java.lang.IllegalArgumentException: character to be escaped is missing                                                                                  
        at java.util.regex.Matcher.appendReplacement(Matcher.java:809) ~[?:1.8.0_222]                                                                              
        at java.util.regex.Matcher.replaceAll(Matcher.java:955) ~[?:1.8.0_222]                                                                                     
        at java.lang.String.replaceAll(String.java:2223) ~[?:1.8.0_222]                                                                                            
        at com.github.aasmus.pvptoggle.utils.Chat.send(Chat.java:28) ~[?:?]                                                                                        
        at com.github.aasmus.pvptoggle.PvPCommand.onCommand(PvPCommand.java:115) ~[?:?]                                                                            
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.4.jar:git-Paper-221]                                                     
        ... 17 more                                  
```

Have a look at the above error. Seems to be an issue with argument parsing.

**Comment by aasmus** [comment]
Have you modified your chat messages in the config? My guess right now would be that a <parameter> is missing from a message string

**Comment by nkomarn** [comment]
I just realized I left important information out of the top. The thing that prompted the error was:
`[16:20:14 INFO]: (player) issued server command: /pvp off\`

So I think the issue is just the `\` is acting like an escape character and thus the error occurs because there is nothing to be escaped.

**Comment by aasmus** [comment]
Ah, yep. I'm really busy at the minute but I'm working on a new version I hope to have done fairly soon. I'll make sure this is fixed in it. Thanks!
