### ISSUE TITLE
[Error] Could not pass event EntityDamageByEntityEvent

### ISSUE THREAD

**Issue by Baktus79** [aasmus/PvPToggle#3]
```
[17:25:51 ERROR]: Could not pass event EntityDamageByEntityEvent to PvPToggle v1.5.3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-405]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-405]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-405]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-405]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:100) ~[patched_1.13.2.jar:git-Paper-405]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:672) ~[patched_1.13.2.jar:git-Paper-405]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:571) ~[patched_1.13.2.jar:git-Paper-405]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:704) ~[patched_1.13.2.jar:git-Paper-405]
        at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity0(EntityLiving.java:1520) ~[patched_1.13.2.jar:git-Paper-405]
        at net.minecraft.server.v1_13_R2.EntityHuman.damageEntity0(EntityHuman.java:911) ~[patched_1.13.2.jar:git-Paper-405]
        at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:993) ~[patched_1.13.2.jar:git-Paper-405]
        at net.minecraft.server.v1_13_R2.EntityHuman.damageEntity(EntityHuman.java:824) ~[patched_1.13.2.jar:git-Paper-405]
        at net.minecraft.server.v1_13_R2.EntityPlayer.damageEntity(EntityPlayer.java:654) ~[patched_1.13.2.jar:git-Paper-405]
        at net.minecraft.server.v1_13_R2.EntityHuman.attack(EntityHuman.java:1086) ~[patched_1.13.2.jar:git-Paper-405]
        at net.minecraft.server.v1_13_R2.EntityPlayer.attack(EntityPlayer.java:1419) ~[patched_1.13.2.jar:git-Paper-405]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1993) ~[patched_1.13.2.jar:git-Paper-405]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.13.2.jar:git-Paper-405]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.13.2.jar:git-Paper-405]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-405]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-405]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-405]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-405]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-405]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-405]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
        at com.github.aasmus.pvptoggle.listeners.PvP.onHit(PvP.java:35) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1010.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-405]
        ... 26 more
```

**PvPToggle version:** 1.5.3
**Server Type:** Paper
**Server Version:** git-Paper-405 (MC: 1.13.2)

**Comment by Baktus79** [comment]
Seems like it stopped after a restart. Everything seems to be working now, and therefor closing this post.
